name: Codecov Build

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: |
          cd project
          mvn --batch-mode --update-snapshots verify -Dresources.path=classpath

      - name: Upload Reports
        run: |
          bash <(curl -s https://codecov.io/bash)
